# Generated by Django 2.1.2 on 2018-10-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_multiplechoicequestion_truefalsequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quizs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Quiz'),
        ),
    ]
