# Generated by Django 2.1.2 on 2018-10-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published',
            new_name='is_live',
        ),
    ]
